export const reportdata = [
  {
    id: 1,
    userId: 101,
    reportType: "spam",
    reportId: 1001,
    reason: "Unsolicited advertising",
    content: "This user keeps posting spam messages.",
    reportDate: "2024-07-15",
    status: "open",
  },
  {
    id: 2,
    userId: 102,
    reportType: "abuse",
    reportId: 1002,
    reason: "Harassment",
    content: "User is sending threatening messages.",
    reportDate: "2024-07-16",
    status: "investigating",
  },
  {
    id: 3,
    userId: 103,
    reportType: "fraud",
    reportId: 1003,
    reason: "Phishing attempt",
    content: "Received a fake email asking for personal information.",
    reportDate: "2024-07-17",
    status: "resolved",
  },
  {
    id: 4,
    userId: 104,
    reportType: "inappropriate",
    reportId: 1004,
    reason: "Offensive content",
    content: "User posted offensive language in comments.",
    reportDate: "2024-07-18",
    status: "open",
  },
  {
    id: 5,
    userId: 105,
    reportType: "spam",
    reportId: 1005,
    reason: "Mass messaging",
    content: "User is sending the same message to many users.",
    reportDate: "2024-07-19",
    status: "investigating",
  },
  {
    id: 6,
    userId: 106,
    reportType: "abuse",
    reportId: 1006,
    reason: "Bullying",
    content: "User is bullying others in chat.",
    reportDate: "2024-07-20",
    status: "open",
  },
  {
    id: 7,
    userId: 107,
    reportType: "fraud",
    reportId: 1007,
    reason: "Scam offer",
    content: "Received an offer that seems too good to be true.",
    reportDate: "2024-07-21",
    status: "resolved",
  },
  {
    id: 8,
    userId: 108,
    reportType: "inappropriate",
    reportId: 1008,
    reason: "Graphic content",
    content: "User shared graphic images.",
    reportDate: "2024-07-22",
    status: "investigating",
  },
  {
    id: 9,
    userId: 109,
    reportType: "spam",
    reportId: 1009,
    reason: "Repeated posts",
    content: "User is repeating posts in multiple forums.",
    reportDate: "2024-07-23",
    status: "open",
  },
  {
    id: 10,
    userId: 110,
    reportType: "abuse",
    reportId: 1010,
    reason: "Verbal abuse",
    content: "User is verbally abusing others.",
    reportDate: "2024-07-24",
    status: "resolved",
  },
  {
    id: 11,
    userId: 111,
    reportType: "fraud",
    reportId: 1011,
    reason: "Fake account",
    content: "Suspected fake account activity.",
    reportDate: "2024-07-25",
    status: "investigating",
  },
  {
    id: 12,
    userId: 112,
    reportType: "inappropriate",
    reportId: 1012,
    reason: "Hate speech",
    content: "User posted hate speech against a group.",
    reportDate: "2024-07-26",
    status: "open",
  },
  {
    id: 13,
    userId: 113,
    reportType: "spam",
    reportId: 1013,
    reason: "Link spamming",
    content: "User is spamming links to external sites.",
    reportDate: "2024-07-27",
    status: "resolved",
  },
  {
    id: 14,
    userId: 114,
    reportType: "abuse",
    reportId: 1014,
    reason: "Racism",
    content: "User made racist remarks.",
    reportDate: "2024-07-28",
    status: "investigating",
  },
  {
    id: 15,
    userId: 115,
    reportType: "fraud",
    reportId: 1015,
    reason: "Identity theft",
    content: "User attempted to steal identity.",
    reportDate: "2024-07-29",
    status: "open",
  },
  {
    id: 16,
    userId: 116,
    reportType: "inappropriate",
    reportId: 1016,
    reason: "Sexual content",
    content: "User shared inappropriate sexual content.",
    reportDate: "2024-07-30",
    status: "resolved",
  },
  {
    id: 17,
    userId: 117,
    reportType: "spam",
    reportId: 1017,
    reason: "Repeated advertisements",
    content: "User repeatedly advertises products.",
    reportDate: "2024-07-31",
    status: "investigating",
  },
  {
    id: 18,
    userId: 118,
    reportType: "abuse",
    reportId: 1018,
    reason: "Stalking",
    content: "User is stalking another user.",
    reportDate: "2024-08-01",
    status: "open",
  },
  {
    id: 19,
    userId: 119,
    reportType: "fraud",
    reportId: 1019,
    reason: "False claims",
    content: "User made false claims about a product.",
    reportDate: "2024-08-02",
    status: "resolved",
  },
  {
    id: 20,
    userId: 120,
    reportType: "inappropriate",
    reportId: 1020,
    reason: "Personal attacks",
    content: "User attacked someone personally.",
    reportDate: "2024-08-02",
    status: "investigating",
  },
]
