export const userdata = [
  {
    id: 1,
    email: "user1@example.com",
    nickname: "coolcat1",
    birth: "1990-01-15",
    phone: "555-1234",
    image: "https://example.com/images/user1.jpg",
    disabled: false,
    role: "user",
    socialType: "facebook",
    socialId: "fb_12345",
  },
  {
    id: 2,
    email: "user2@example.com",
    nickname: "funkyfish2",
    birth: "1988-03-22",
    phone: "555-5678",
    image: "https://example.com/images/user2.jpg",
    disabled: false,
    role: "admin",
    socialType: "google",
    socialId: "google_67890",
  },
  {
    id: 3,
    email: "user3@example.com",
    nickname: "sunnybird3",
    birth: "1995-07-11",
    phone: "555-9101",
    image: "https://example.com/images/user3.jpg",
    disabled: false,
    role: "user",
    socialType: "twitter",
    socialId: "twitter_11111",
  },
  {
    id: 4,
    email: "user4@example.com",
    nickname: "happyfrog4",
    birth: "1992-02-09",
    phone: "555-1213",
    image: "https://example.com/images/user4.jpg",
    disabled: true,
    role: "user",
    socialType: "facebook",
    socialId: "fb_22222",
  },
  {
    id: 5,
    email: "user5@example.com",
    nickname: "flyingtiger5",
    birth: "1985-12-30",
    phone: "555-1415",
    image: "https://example.com/images/user5.jpg",
    disabled: false,
    role: "user",
    socialType: "google",
    socialId: "google_33333",
  },
  {
    id: 6,
    email: "user6@example.com",
    nickname: "silverfox6",
    birth: "1997-05-24",
    phone: "555-1617",
    image: "https://example.com/images/user6.jpg",
    disabled: false,
    role: "user",
    socialType: "twitter",
    socialId: "twitter_44444",
  },
  {
    id: 7,
    email: "user7@example.com",
    nickname: "gentlewhale7",
    birth: "1993-08-19",
    phone: "555-1819",
    image: "https://example.com/images/user7.jpg",
    disabled: false,
    role: "user",
    socialType: "facebook",
    socialId: "fb_55555",
  },
  {
    id: 8,
    email: "user8@example.com",
    nickname: "swiftowl8",
    birth: "1991-06-13",
    phone: "555-2021",
    image: "https://example.com/images/user8.jpg",
    disabled: true,
    role: "user",
    socialType: "google",
    socialId: "google_66666",
  },
  {
    id: 9,
    email: "user9@example.com",
    nickname: "bravewolf9",
    birth: "1989-11-07",
    phone: "555-2223",
    image: "https://example.com/images/user9.jpg",
    disabled: false,
    role: "admin",
    socialType: "twitter",
    socialId: "twitter_77777",
  },
  {
    id: 10,
    email: "user10@example.com",
    nickname: "nobledeer10",
    birth: "1994-03-28",
    phone: "555-2425",
    image: "https://example.com/images/user10.jpg",
    disabled: false,
    role: "user",
    socialType: "facebook",
    socialId: "fb_88888",
  },
  {
    id: 11,
    email: "user11@example.com",
    nickname: "quickrabbit11",
    birth: "1998-10-14",
    phone: "555-2627",
    image: "https://example.com/images/user11.jpg",
    disabled: false,
    role: "user",
    socialType: "google",
    socialId: "google_99999",
  },
  {
    id: 12,
    email: "user12@example.com",
    nickname: "wiseowl12",
    birth: "1996-04-05",
    phone: "555-2829",
    image: "https://example.com/images/user12.jpg",
    disabled: false,
    role: "user",
    socialType: "twitter",
    socialId: "twitter_10101",
  },
  {
    id: 13,
    email: "user13@example.com",
    nickname: "boldlion13",
    birth: "1987-07-09",
    phone: "555-3031",
    image: "https://example.com/images/user13.jpg",
    disabled: true,
    role: "user",
    socialType: "facebook",
    socialId: "fb_12121",
  },
  {
    id: 14,
    email: "user14@example.com",
    nickname: "smartsquirrel14",
    birth: "1990-09-21",
    phone: "555-3233",
    image: "https://example.com/images/user14.jpg",
    disabled: false,
    role: "user",
    socialType: "google",
    socialId: "google_13131",
  },
  {
    id: 15,
    email: "user15@example.com",
    nickname: "brightstar15",
    birth: "1986-06-29",
    phone: "555-3435",
    image: "https://example.com/images/user15.jpg",
    disabled: false,
    role: "admin",
    socialType: "twitter",
    socialId: "twitter_14141",
  },
  {
    id: 16,
    email: "user16@example.com",
    nickname: "mightybear16",
    birth: "1988-02-02",
    phone: "555-3637",
    image: "https://example.com/images/user16.jpg",
    disabled: false,
    role: "user",
    socialType: "facebook",
    socialId: "fb_15151",
  },
  {
    id: 17,
    email: "user17@example.com",
    nickname: "sneakypanda17",
    birth: "1992-11-17",
    phone: "555-3839",
    image: "https://example.com/images/user17.jpg",
    disabled: true,
    role: "user",
    socialType: "google",
    socialId: "google_16161",
  },
  {
    id: 18,
    email: "user18@example.com",
    nickname: "royaltiger18",
    birth: "1985-05-12",
    phone: "555-4041",
    image: "https://example.com/images/user18.jpg",
    disabled: false,
    role: "user",
    socialType: "twitter",
    socialId: "twitter_17171",
  },
  {
    id: 19,
    email: "user19@example.com",
    nickname: "kindpanda19",
    birth: "1993-01-30",
    phone: "555-4243",
    image: "https://example.com/images/user19.jpg",
    disabled: false,
    role: "user",
    socialType: "facebook",
    socialId: "fb_18181",
  },
]
