const dummyData = [
  {
    id: 1,
    user_id: 101,
    post_id: 201,
    animal_id: 301,
    title: "우리 집 고양이가 재미있는 짓을 해요",
    thumbnail: "img1.jpg",
    content: "우리 고양이가 새 장난감으로 놀아요! 정말 귀엽죠?",
    regist_time: "2024-07-24T09:00:00Z",
    nickname: "고양이사랑",
    image: "img1.jpg",
  },
  {
    id: 2,
    user_id: 102,
    post_id: 202,
    animal_id: 302,
    title: "우리 강아지와 함께한 즐거운 시간",
    thumbnail: "img2.jpg",
    content:
      "오늘은 우리 강아지와 함께 공원에서 산책을 했어요. 너무 기분 좋았어요!",
    regist_time: "2024-07-24T09:15:00Z",
    nickname: "반려견행복",
    image: "img2.jpg",
  },
  {
    id: 3,
    user_id: 103,
    post_id: 203,
    animal_id: 303,
    title: "첫 번째 털뭉치들과의 첫 만남",
    thumbnail: "img3.jpg",
    content: "오늘 우리 가족에 새로운 구성원이 늘었어요! 환영해주세요.",
    regist_time: "2024-07-24T09:30:00Z",
    nickname: "새로운가족",
    image: "img3.jpg",
  },
  {
    id: 4,
    user_id: 104,
    post_id: 204,
    animal_id: 304,
    title: "자유롭게 하늘을 날다",
    thumbnail: "img4.jpg",
    content: "오늘 우리 앵무새가 자유롭게 하늘을 날아다녀요. 정말 멋지죠?",
    regist_time: "2024-07-24T09:45:00Z",
    nickname: "앵무새의자유",
    image: "img4.jpg",
  },
  {
    id: 5,
    user_id: 105,
    post_id: 205,
    animal_id: 305,
    title: "꽃과 나비의 아름다운 만남",
    thumbnail: "img5.jpg",
    content:
      "오늘 정원에서 아름다운 꽃과 나비들을 만났어요. 자연의 아름다움에 감동했어요!",
    regist_time: "2024-07-24T10:00:00Z",
    nickname: "자연의아름다움",
    image: "img5.jpg",
  },
  {
    id: 6,
    user_id: 106,
    post_id: 206,
    animal_id: 306,
    title: "여름 햇살 아래 우리 집 고양이",
    thumbnail: "img6.jpg",
    content: "우리 고양이가 창가에 앉아 햇살을 쬐고 있어요. 너무 귀엽죠?",
    regist_time: "2024-07-24T10:15:00Z",
    nickname: "햇살좋은날",
    image: "img6.jpg",
  },
  {
    id: 7,
    user_id: 107,
    post_id: 207,
    animal_id: 307,
    title: "초록빛 자연 속에서 우리 강아지와 함께",
    thumbnail: "img7.jpg",
    content:
      "오늘은 산책을 통해 자연 속에서 새로운 발견을 했어요. 행복한 시간이었어요!",
    regist_time: "2024-07-24T10:30:00Z",
    nickname: "산책자연",
    image: "img7.jpg",
  },
  {
    id: 8,
    user_id: 108,
    post_id: 208,
    animal_id: 308,
    title: "평온한 호수에서 물고기와 함께",
    thumbnail: "img8.jpg",
    content:
      "오늘은 호수에서 평온한 시간을 보냈어요. 물고기와 함께 자연 속을 즐겼어요.",
    regist_time: "2024-07-24T10:45:00Z",
    nickname: "호수의평온",
    image: "img8.jpg",
  },
  {
    id: 9,
    user_id: 109,
    post_id: 209,
    animal_id: 309,
    title: "바람을 맞으며 들판을 달리는 말들",
    thumbnail: "img9.jpg",
    content:
      "말들이 바람을 맞으며 들판을 달리는 모습이 너무 멋있었어요. 자유로움이 느껴졌어요!",
    regist_time: "2024-07-24T11:00:00Z",
    nickname: "말의자유",
    image: "img9.jpg",
  },
  {
    id: 10,
    user_id: 110,
    post_id: 210,
    animal_id: 310,
    title: "천천히 흐르는 시간 속에서",
    thumbnail: "img10.jpg",
    content:
      "천천히 흐르는 시간 속에서 자연의 소리와 함께 여유를 느꼈어요. 힐링타임이었어요.",
    regist_time: "2024-07-24T11:15:00Z",
    nickname: "자연의소리",
    image: "img10.jpg",
  },
]

export default dummyData
