const dummyData = [
  {
    id: 1,
    user_id: 101,
    post_id: 201,
    animal_id: 301,
    petname: "냥냥이",
    kind_cd: "[고양이] 코리안 숏헤어",
    color_cd: "회색",
    sex_cd: "암컷",
    process_state: "입양가능",
    title: "입양 가능한 사랑스러운 코리안 숏헤어를 소개합니다!",
    thumbnail: "img1.jpg",
    content: "우리 고양이가 새 장난감으로 놀아요! 정말 귀엽죠?",
    registTime: "2024-07-24T09:00:00Z",
    userNickName: "고양이사랑",
    userImage: "img1.jpg",
    age: "2018년생",
  },
  {
    id: 2,
    user_id: 102,
    post_id: 202,
    animal_id: 302,
    petname: "뭉치",
    kind_cd: "[개] 말티즈",
    color_cd: "흰색",
    sex_cd: "수컷",
    process_state: "입양중",
    title: "우리 강아지와의 즐거운 산책 후기 공유합니다!",
    thumbnail: "img2.jpg",
    content:
      "오늘은 우리 강아지와 함께 공원에서 산책을 했어요. 너무 기분 좋았어요!",
    registTime: "2024-07-24T09:15:00Z",
    userNickName: "반려견행복",
    userImage: "img2.jpg",
    age: "2017년생",
  },
  {
    id: 3,
    user_id: 103,
    post_id: 203,
    animal_id: 303,
    petname: "보리",
    kind_cd: "[고양이] 샴",
    color_cd: "갈색",
    sex_cd: "암컷",
    process_state: "임시보호",
    title: "새로운 가족 구성원, 샴 고양이 보리의 첫 날!",
    thumbnail: "img3.jpg",
    content: "오늘 우리 가족에 새로운 구성원이 늘었어요! 환영해주세요.",
    registTime: "2024-07-24T09:30:00Z",
    userNickName: "새로운가족",
    userImage: "img3.jpg",
    age: "2019년생",
  },
  {
    id: 4,
    user_id: 104,
    post_id: 204,
    animal_id: 304,
    petname: "바비",
    kind_cd: "[개] 비글",
    color_cd: "갈색과 흰색",
    sex_cd: "수컷",
    process_state: "보호중",
    title: "자유롭게 하늘을 나는 앵무새 바비의 일상",
    thumbnail: "img4.jpg",
    content: "오늘 우리 앵무새가 자유롭게 하늘을 날아다녀요. 정말 멋지죠?",
    registTime: "2024-07-24T09:45:00Z",
    userNickName: "앵무새의자유",
    userImage: "img4.jpg",
    age: "2020년생",
  },
  {
    id: 5,
    user_id: 105,
    post_id: 205,
    animal_id: 305,
    petname: "초코",
    kind_cd: "[고양이] 러시안 블루",
    color_cd: "청회색",
    sex_cd: "암컷",
    process_state: "입양완료",
    title: "자연의 아름다움을 만끽하는 러시안 블루 초코의 이야기",
    thumbnail: "img5.jpg",
    content:
      "오늘 정원에서 아름다운 꽃과 나비들을 만났어요. 자연의 아름다움에 감동했어요!",
    registTime: "2024-07-24T10:00:00Z",
    userNickName: "자연의아름다움",
    userImage: "img5.jpg",
    age: "2018년생",
  },
  {
    id: 6,
    user_id: 106,
    post_id: 206,
    animal_id: 306,
    petname: "고미",
    kind_cd: "[고양이] 페르시안",
    color_cd: "검은색",
    sex_cd: "수컷",
    process_state: "입양중",
    title: "햇살 좋은 날, 페르시안 고양이 고미의 평화로운 순간",
    thumbnail: "img6.jpg",
    content: "우리 고양이가 창가에 앉아 햇살을 쬐고 있어요. 너무 귀엽죠?",
    registTime: "2024-07-24T10:15:00Z",
    userNickName: "햇살좋은날",
    userImage: "img6.jpg",
    age: "2016년생",
  },
  {
    id: 7,
    user_id: 107,
    post_id: 207,
    animal_id: 307,
    petname: "하루",
    kind_cd: "[개] 시바 이누",
    color_cd: "황갈색",
    sex_cd: "암컷",
    process_state: "입양가능",
    title: "자연 속에서 하루와의 행복한 산책 이야기",
    thumbnail: "img7.jpg",
    content:
      "오늘은 산책을 통해 자연 속에서 새로운 발견을 했어요. 행복한 시간이었어요!",
    registTime: "2024-07-24T10:30:00Z",
    userNickName: "산책자연",
    userImage: "img7.jpg",
    age: "2019년생",
  },
  {
    id: 8,
    user_id: 108,
    post_id: 208,
    animal_id: 308,
    petname: "해피",
    kind_cd: "[개] 골든 리트리버",
    color_cd: "금색",
    sex_cd: "수컷",
    process_state: "보호중",
    title: "골든 리트리버 해피와의 평온한 호수 여행",
    thumbnail: "img8.jpg",
    content:
      "오늘은 호수에서 평온한 시간을 보냈어요. 물고기와 함께 자연 속을 즐겼어요.",
    registTime: "2024-07-24T10:45:00Z",
    userNickName: "호수의평온",
    userImage: "img8.jpg",
    age: "2018년생",
  },
  {
    id: 9,
    user_id: 109,
    post_id: 209,
    animal_id: 309,
    petname: "브라운",
    kind_cd: "[개] 보더 콜리",
    color_cd: "갈색",
    sex_cd: "수컷",
    process_state: "입양완료",
    title: "자유를 만끽하는 보더 콜리 브라운의 멋진 모습",
    thumbnail: "img9.jpg",
    content:
      "말들이 바람을 맞으며 들판을 달리는 모습이 너무 멋있었어요. 자유로움이 느껴졌어요!",
    registTime: "2024-07-24T11:00:00Z",
    userNickName: "말의자유",
    userImage: "img9.jpg",
    age: "2017년생",
  },
  {
    id: 10,
    user_id: 110,
    post_id: 210,
    animal_id: 310,
    petname: "바람",
    kind_cd: "[고양이] 터키시 앙고라",
    color_cd: "회색",
    sex_cd: "암컷",
    process_state: "임시보호",
    title: "터키시 앙고라 바람의 평화로운 힐링 타임",
    thumbnail: "img10.jpg",
    content:
      "천천히 흐르는 시간 속에서 자연의 시간 속에서 자연의 시간 속에서 자연의 시간 속에서 자연의 시간 속에서 자연의 시간 속에서 자연의 시간 속에서 자연의 시간 속에서 자연의 소리와 함께 여유를 느꼈어요. 힐링타임이었어요.",
    registTime: "2024-07-24T11:15:00Z",
    userNickName: "자연의소리",
    userImage: "img10.jpg",
    age: "2016년생",
  },
]

export default dummyData
