const data = [
  {
    id: "1",
    userId: "user1",
    boardId: "1",
    animalId: "animal1",
    title: "귀여운 강아지",
    content: "이 귀여운 강아지를 보세요!",
    thumbnail: "thumbnail1.jpg",
    video: "cat.mp4",
    registTime: "2023-08-01T10:00:00",
    userImage: "user1.jpg",
    like: true,
    follow: false,
    comments: [
      {
        id: 1,
        userId: 1,
        petPickId: 1,
        content: "정말 귀여워요!",
        registTime: "2023-08-01T10:01:00",
        userImage: "commenter1.jpg",
      },
      {
        id: 2,
        userId: 2,
        petPickId: 1,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-01T10:02:00",
        userImage: "commenter2.jpg",
      },
      {
        id: 3,
        userId: 3,
        petPickId: 1,
        content: "완전 좋아요!",
        registTime: "2023-08-01T10:03:00",
        userImage: "commenter3.jpg",
      },
      {
        id: 4,
        userId: 4,
        petPickId: 1,
        content: "너무 소중해요!",
        registTime: "2023-08-01T10:04:00",
        userImage: "commenter4.jpg",
      },
      {
        id: 5,
        userId: 5,
        petPickId: 1,
        content: "사랑스러워요!",
        registTime: "2023-08-01T10:05:00",
        userImage: "commenter5.jpg",
      },
      {
        id: 6,
        userId: 6,
        petPickId: 1,
        content: "너무 귀여워요!",
        registTime: "2023-08-01T10:06:00",
        userImage: "commenter6.jpg",
      },
      {
        id: 7,
        userId: 7,
        petPickId: 1,
        content: "이 강아지 너무 사랑스러워요!",
        registTime: "2023-08-01T10:07:00",
        userImage: "commenter7.jpg",
      },
      {
        id: 8,
        userId: 8,
        petPickId: 1,
        content: "정말 아름다워요!",
        registTime: "2023-08-01T10:08:00",
        userImage: "commenter8.jpg",
      },
      {
        id: 9,
        userId: 9,
        petPickId: 1,
        content: "완전 귀여워요!",
        registTime: "2023-08-01T10:09:00",
        userImage: "commenter9.jpg",
      },
      {
        id: 10,
        userId: 10,
        petPickId: 1,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-01T10:10:00",
        userImage: "commenter10.jpg",
      },
      {
        id: 11,
        userId: 11,
        petPickId: 1,
        content: "이 강아지 정말 귀여워요!",
        registTime: "2023-08-01T10:11:00",
        userImage: "commenter11.jpg",
      },
      {
        id: 12,
        userId: 12,
        petPickId: 1,
        content: "정말 사랑스러워요!",
        registTime: "2023-08-01T10:12:00",
        userImage: "commenter12.jpg",
      },
    ],
  },
  {
    id: "2",
    userId: "user2",
    boardId: "2",
    animalId: "animal2",
    title: "멋진 고양이",
    content: "이 멋진 고양이를 보세요!",
    thumbnail: "thumbnail2.jpg",
    video: "cat.mp4",
    registTime: "2023-08-02T11:00:00",
    userImage: "user2.jpg",
    like: false,
    follow: true,
    comments: [
      {
        id: 1,
        userId: 1,
        petPickId: 2,
        content: "정말 멋져요!",
        registTime: "2023-08-02T11:01:00",
        userImage: "commenter1.jpg",
      },
      {
        id: 2,
        userId: 2,
        petPickId: 2,
        content: "너무 아름다워요!",
        registTime: "2023-08-02T11:02:00",
        userImage: "commenter2.jpg",
      },
      {
        id: 3,
        userId: 3,
        petPickId: 2,
        content: "완전 멋져요!",
        registTime: "2023-08-02T11:03:00",
        userImage: "commenter3.jpg",
      },
      {
        id: 4,
        userId: 4,
        petPickId: 2,
        content: "너무 소중해요!",
        registTime: "2023-08-02T11:04:00",
        userImage: "commenter4.jpg",
      },
      {
        id: 5,
        userId: 5,
        petPickId: 2,
        content: "사랑스러워요!",
        registTime: "2023-08-02T11:05:00",
        userImage: "commenter5.jpg",
      },
      {
        id: 6,
        userId: 6,
        petPickId: 2,
        content: "너무 멋져요!",
        registTime: "2023-08-02T11:06:00",
        userImage: "commenter6.jpg",
      },
      {
        id: 7,
        userId: 7,
        petPickId: 2,
        content: "이 고양이 너무 사랑스러워요!",
        registTime: "2023-08-02T11:07:00",
        userImage: "commenter7.jpg",
      },
      {
        id: 8,
        userId: 8,
        petPickId: 2,
        content: "정말 아름다워요!",
        registTime: "2023-08-02T11:08:00",
        userImage: "commenter8.jpg",
      },
      {
        id: 9,
        userId: 9,
        petPickId: 2,
        content: "완전 멋져요!",
        registTime: "2023-08-02T11:09:00",
        userImage: "commenter9.jpg",
      },
      {
        id: 10,
        userId: 10,
        petPickId: 2,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-02T11:10:00",
        userImage: "commenter10.jpg",
      },
      {
        id: 11,
        userId: 11,
        petPickId: 2,
        content: "이 고양이 정말 멋져요!",
        registTime: "2023-08-02T11:11:00",
        userImage: "commenter11.jpg",
      },
      {
        id: 12,
        userId: 12,
        petPickId: 2,
        content: "정말 사랑스러워요!",
        registTime: "2023-08-02T11:12:00",
        userImage: "commenter12.jpg",
      },
    ],
  },
  {
    id: "3",
    userId: "user3",
    boardId: "3",
    animalId: "animal3",
    title: "귀여운 햄스터",
    content: "이 귀여운 햄스터를 보세요!",
    thumbnail: "thumbnail3.jpg",
    video: "cat.mp4",
    registTime: "2023-08-03T12:00:00",
    userImage: "user3.jpg",
    like: true,
    follow: true,
    comments: [
      {
        id: 1,
        userId: 1,
        petPickId: 3,
        content: "정말 귀여워요!",
        registTime: "2023-08-03T12:01:00",
        userImage: "commenter1.jpg",
      },
      {
        id: 2,
        userId: 2,
        petPickId: 3,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-03T12:02:00",
        userImage: "commenter2.jpg",
      },
      {
        id: 3,
        userId: 3,
        petPickId: 3,
        content: "완전 좋아요!",
        registTime: "2023-08-03T12:03:00",
        userImage: "commenter3.jpg",
      },
      {
        id: 4,
        userId: 4,
        petPickId: 3,
        content: "너무 소중해요!",
        registTime: "2023-08-03T12:04:00",
        userImage: "commenter4.jpg",
      },
      {
        id: 5,
        userId: 5,
        petPickId: 3,
        content: "사랑스러워요!",
        registTime: "2023-08-03T12:05:00",
        userImage: "commenter5.jpg",
      },
      {
        id: 6,
        userId: 6,
        petPickId: 3,
        content: "너무 귀여워요!",
        registTime: "2023-08-03T12:06:00",
        userImage: "commenter6.jpg",
      },
      {
        id: 7,
        userId: 7,
        petPickId: 3,
        content: "이 햄스터 너무 사랑스러워요!",
        registTime: "2023-08-03T12:07:00",
        userImage: "commenter7.jpg",
      },
      {
        id: 8,
        userId: 8,
        petPickId: 3,
        content: "정말 아름다워요!",
        registTime: "2023-08-03T12:08:00",
        userImage: "commenter8.jpg",
      },
      {
        id: 9,
        userId: 9,
        petPickId: 3,
        content: "완전 귀여워요!",
        registTime: "2023-08-03T12:09:00",
        userImage: "commenter9.jpg",
      },
      {
        id: 10,
        userId: 10,
        petPickId: 3,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-03T12:10:00",
        userImage: "commenter10.jpg",
      },
      {
        id: 11,
        userId: 11,
        petPickId: 3,
        content: "이 햄스터 정말 귀여워요!",
        registTime: "2023-08-03T12:11:00",
        userImage: "commenter11.jpg",
      },
      {
        id: 12,
        userId: 12,
        petPickId: 3,
        content: "정말 사랑스러워요!",
        registTime: "2023-08-03T12:12:00",
        userImage: "commenter12.jpg",
      },
    ],
  },
  {
    id: "4",
    userId: "user4",
    boardId: "4",
    animalId: "animal4",
    title: "장난감 토끼",
    content: "이 장난감 토끼를 보세요!",
    thumbnail: "thumbnail4.jpg",
    video: "cat.mp4",
    registTime: "2023-08-04T13:00:00",
    userImage: "user4.jpg",
    like: true,
    follow: false,
    comments: [
      {
        id: 1,
        userId: 1,
        petPickId: 4,
        content: "정말 멋져요!",
        registTime: "2023-08-04T13:01:00",
        userImage: "commenter1.jpg",
      },
      {
        id: 2,
        userId: 2,
        petPickId: 4,
        content: "너무 아름다워요!",
        registTime: "2023-08-04T13:02:00",
        userImage: "commenter2.jpg",
      },
      {
        id: 3,
        userId: 3,
        petPickId: 4,
        content: "완전 멋져요!",
        registTime: "2023-08-04T13:03:00",
        userImage: "commenter3.jpg",
      },
      {
        id: 4,
        userId: 4,
        petPickId: 4,
        content: "너무 소중해요!",
        registTime: "2023-08-04T13:04:00",
        userImage: "commenter4.jpg",
      },
      {
        id: 5,
        userId: 5,
        petPickId: 4,
        content: "사랑스러워요!",
        registTime: "2023-08-04T13:05:00",
        userImage: "commenter5.jpg",
      },
      {
        id: 6,
        userId: 6,
        petPickId: 4,
        content: "너무 멋져요!",
        registTime: "2023-08-04T13:06:00",
        userImage: "commenter6.jpg",
      },
      {
        id: 7,
        userId: 7,
        petPickId: 4,
        content: "이 토끼 너무 사랑스러워요!",
        registTime: "2023-08-04T13:07:00",
        userImage: "commenter7.jpg",
      },
      {
        id: 8,
        userId: 8,
        petPickId: 4,
        content: "정말 아름다워요!",
        registTime: "2023-08-04T13:08:00",
        userImage: "commenter8.jpg",
      },
      {
        id: 9,
        userId: 9,
        petPickId: 4,
        content: "완전 멋져요!",
        registTime: "2023-08-04T13:09:00",
        userImage: "commenter9.jpg",
      },
      {
        id: 10,
        userId: 10,
        petPickId: 4,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-04T13:10:00",
        userImage: "commenter10.jpg",
      },
      {
        id: 11,
        userId: 11,
        petPickId: 4,
        content: "이 토끼 정말 멋져요!",
        registTime: "2023-08-04T13:11:00",
        userImage: "commenter11.jpg",
      },
      {
        id: 12,
        userId: 12,
        petPickId: 4,
        content: "정말 사랑스러워요!",
        registTime: "2023-08-04T13:12:00",
        userImage: "commenter12.jpg",
      },
    ],
  },
  {
    id: "5",
    userId: "user5",
    boardId: "5",
    animalId: "animal5",
    title: "귀여운 고양이",
    content: "이 귀여운 고양이를 보세요!",
    thumbnail: "thumbnail5.jpg",
    video: "cat.mp4",
    registTime: "2023-08-05T14:00:00",
    userImage: "user5.jpg",
    like: false,
    follow: true,
    comments: [
      {
        id: 1,
        userId: 1,
        petPickId: 5,
        content: "정말 귀여워요!",
        registTime: "2023-08-05T14:01:00",
        userImage: "commenter1.jpg",
      },
      {
        id: 2,
        userId: 2,
        petPickId: 5,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-05T14:02:00",
        userImage: "commenter2.jpg",
      },
      {
        id: 3,
        userId: 3,
        petPickId: 5,
        content: "완전 좋아요!",
        registTime: "2023-08-05T14:03:00",
        userImage: "commenter3.jpg",
      },
      {
        id: 4,
        userId: 4,
        petPickId: 5,
        content: "너무 소중해요!",
        registTime: "2023-08-05T14:04:00",
        userImage: "commenter4.jpg",
      },
      {
        id: 5,
        userId: 5,
        petPickId: 5,
        content: "사랑스러워요!",
        registTime: "2023-08-05T14:05:00",
        userImage: "commenter5.jpg",
      },
      {
        id: 6,
        userId: 6,
        petPickId: 5,
        content: "너무 귀여워요!",
        registTime: "2023-08-05T14:06:00",
        userImage: "commenter6.jpg",
      },
      {
        id: 7,
        userId: 7,
        petPickId: 5,
        content: "이 고양이 너무 사랑스러워요!",
        registTime: "2023-08-05T14:07:00",
        userImage: "commenter7.jpg",
      },
      {
        id: 8,
        userId: 8,
        petPickId: 5,
        content: "정말 아름다워요!",
        registTime: "2023-08-05T14:08:00",
        userImage: "commenter8.jpg",
      },
      {
        id: 9,
        userId: 9,
        petPickId: 5,
        content: "완전 귀여워요!",
        registTime: "2023-08-05T14:09:00",
        userImage: "commenter9.jpg",
      },
      {
        id: 10,
        userId: 10,
        petPickId: 5,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-05T14:10:00",
        userImage: "commenter10.jpg",
      },
      {
        id: 11,
        userId: 11,
        petPickId: 5,
        content: "이 고양이 정말 귀여워요!",
        registTime: "2023-08-05T14:11:00",
        userImage: "commenter11.jpg",
      },
      {
        id: 12,
        userId: 12,
        petPickId: 5,
        content: "정말 사랑스러워요!",
        registTime: "2023-08-05T14:12:00",
        userImage: "commenter12.jpg",
      },
    ],
  },
  {
    id: "6",
    userId: "user6",
    boardId: "6",
    animalId: "animal6",
    title: "재밌는 강아지",
    content: "이 재밌는 강아지를 보세요!",
    thumbnail: "thumbnail6.jpg",
    video: "cat.mp4",
    registTime: "2023-08-06T15:00:00",
    userImage: "user6.jpg",
    like: true,
    follow: false,
    comments: [
      {
        id: 1,
        userId: 1,
        petPickId: 6,
        content: "정말 재밌어요!",
        registTime: "2023-08-06T15:01:00",
        userImage: "commenter1.jpg",
      },
      {
        id: 2,
        userId: 2,
        petPickId: 6,
        content: "너무 웃겨요!",
        registTime: "2023-08-06T15:02:00",
        userImage: "commenter2.jpg",
      },
      {
        id: 3,
        userId: 3,
        petPickId: 6,
        content: "완전 웃겨요!",
        registTime: "2023-08-06T15:03:00",
        userImage: "commenter3.jpg",
      },
      {
        id: 4,
        userId: 4,
        petPickId: 6,
        content: "너무 재밌어요!",
        registTime: "2023-08-06T15:04:00",
        userImage: "commenter4.jpg",
      },
      {
        id: 5,
        userId: 5,
        petPickId: 6,
        content: "웃겨요!",
        registTime: "2023-08-06T15:05:00",
        userImage: "commenter5.jpg",
      },
      {
        id: 6,
        userId: 6,
        petPickId: 6,
        content: "너무 재밌어요!",
        registTime: "2023-08-06T15:06:00",
        userImage: "commenter6.jpg",
      },
      {
        id: 7,
        userId: 7,
        petPickId: 6,
        content: "이 강아지 너무 웃겨요!",
        registTime: "2023-08-06T15:07:00",
        userImage: "commenter7.jpg",
      },
      {
        id: 8,
        userId: 8,
        petPickId: 6,
        content: "정말 재밌어요!",
        registTime: "2023-08-06T15:08:00",
        userImage: "commenter8.jpg",
      },
      {
        id: 9,
        userId: 9,
        petPickId: 6,
        content: "완전 재밌어요!",
        registTime: "2023-08-06T15:09:00",
        userImage: "commenter9.jpg",
      },
      {
        id: 10,
        userId: 10,
        petPickId: 6,
        content: "너무 웃겨요!",
        registTime: "2023-08-06T15:10:00",
        userImage: "commenter10.jpg",
      },
      {
        id: 11,
        userId: 11,
        petPickId: 6,
        content: "이 강아지 정말 재밌어요!",
        registTime: "2023-08-06T15:11:00",
        userImage: "commenter11.jpg",
      },
      {
        id: 12,
        userId: 12,
        petPickId: 6,
        content: "정말 웃겨요!",
        registTime: "2023-08-06T15:12:00",
        userImage: "commenter12.jpg",
      },
    ],
  },
  {
    id: "7",
    userId: "user7",
    boardId: "7",
    animalId: "animal7",
    title: "귀여운 새끼 고양이",
    content: "이 귀여운 새끼 고양이를 보세요!",
    thumbnail: "thumbnail7.jpg",
    video: "cat.mp4",
    registTime: "2023-08-07T16:00:00",
    userImage: "user7.jpg",
    like: false,
    follow: true,
    comments: [
      {
        id: 1,
        userId: 1,
        petPickId: 7,
        content: "정말 귀여워요!",
        registTime: "2023-08-07T16:01:00",
        userImage: "commenter1.jpg",
      },
      {
        id: 2,
        userId: 2,
        petPickId: 7,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-07T16:02:00",
        userImage: "commenter2.jpg",
      },
      {
        id: 3,
        userId: 3,
        petPickId: 7,
        content: "완전 좋아요!",
        registTime: "2023-08-07T16:03:00",
        userImage: "commenter3.jpg",
      },
      {
        id: 4,
        userId: 4,
        petPickId: 7,
        content: "너무 소중해요!",
        registTime: "2023-08-07T16:04:00",
        userImage: "commenter4.jpg",
      },
      {
        id: 5,
        userId: 5,
        petPickId: 7,
        content: "사랑스러워요!",
        registTime: "2023-08-07T16:05:00",
        userImage: "commenter5.jpg",
      },
      {
        id: 6,
        userId: 6,
        petPickId: 7,
        content: "너무 귀여워요!",
        registTime: "2023-08-07T16:06:00",
        userImage: "commenter6.jpg",
      },
      {
        id: 7,
        userId: 7,
        petPickId: 7,
        content: "이 새끼 고양이 너무 사랑스러워요!",
        registTime: "2023-08-07T16:07:00",
        userImage: "commenter7.jpg",
      },
      {
        id: 8,
        userId: 8,
        petPickId: 7,
        content: "정말 아름다워요!",
        registTime: "2023-08-07T16:08:00",
        userImage: "commenter8.jpg",
      },
      {
        id: 9,
        userId: 9,
        petPickId: 7,
        content: "완전 귀여워요!",
        registTime: "2023-08-07T16:09:00",
        userImage: "commenter9.jpg",
      },
      {
        id: 10,
        userId: 10,
        petPickId: 7,
        content: "너무 사랑스러워요!",
        registTime: "2023-08-07T16:10:00",
        userImage: "commenter10.jpg",
      },
      {
        id: 11,
        userId: 11,
        petPickId: 7,
        content: "이 새끼 고양이 정말 귀여워요!",
        registTime: "2023-08-07T16:11:00",
        userImage: "commenter11.jpg",
      },
      {
        id: 12,
        userId: 12,
        petPickId: 7,
        content: "정말 사랑스러워요!",
        registTime: "2023-08-07T16:12:00",
        userImage: "commenter12.jpg",
      },
    ],
  },
]

export default data
