const data = [
  {
    id: "1",
    userId: "1",
    boardId: "1",
    animalId: "1",
    title: "Cute Cat Video 1",
    content: "This is an adorable video of my cat playing around.",
    thumbnail: "/thumbnails/cat1.jpg",
    video: "/petpicks/cat.mp4",
    registTime: "2024-08-03T12:00:00",
    userNickname: "CatLover1",
    userImage: "/images/user1.jpg",
    likeCnt: 50,
    isLiking: true,
    isFollowing: false,
    processState: "입양대기",
    kindCd: "[개] 말티즈",
    name: "Whiskers",
    comments: [
      {
        id: 1,
        userId: 1,
        petPickId: 1,
        content: "So cute! Love this video!",
        registTime: "2024-08-03T13:00:00",
        userNickname: "PetFan1",
        userImage: "/images/commenter1.jpg",
      },
      {
        id: 2,
        userId: 2,
        petPickId: 1,
        content: "My cat loves watching this too!",
        registTime: "2024-08-03T14:00:00",
        userNickname: "PetLover2",
        userImage: "/images/commenter2.jpg",
      },
      {
        id: 3,
        userId: 3,
        petPickId: 1,
        content: "Great video! Thanks for sharing.",
        registTime: "2024-08-03T15:00:00",
        userNickname: "CatFan3",
        userImage: "/images/commenter3.jpg",
      },
    ],
  },
  {
    id: "2",
    userId: "2",
    boardId: "2",
    animalId: "2",
    title: "Funny Dog Video",
    content: "Watch this hilarious video of my dog doing tricks.",
    thumbnail: "/thumbnails/dog1.jpg",
    video: "/petpicks/video1.mp4",
    registTime: "2024-08-03T16:00:00",
    userNickname: "DogLover1",
    userImage: "/images/user2.jpg",
    likeCnt: 75,
    isLiking: false,
    isFollowing: true,
    processState: "임시보호",
    kindCd: "[개] 불독",
    name: "Rex",
    comments: [
      {
        id: 4,
        userId: 4,
        petPickId: 2,
        content: "This is so funny! Loved the tricks.",
        registTime: "2024-08-03T17:00:00",
        userNickname: "DogFan4",
        userImage: "/images/commenter4.jpg",
      },
      {
        id: 5,
        userId: 5,
        petPickId: 2,
        content: "My dog tried to mimic the tricks!",
        registTime: "2024-08-03T18:00:00",
        userNickname: "DogLover5",
        userImage: "/images/commenter5.jpg",
      },
      {
        id: 6,
        userId: 6,
        petPickId: 2,
        content: "Love this! More videos please.",
        registTime: "2024-08-03T19:00:00",
        userNickname: "DogFan6",
        userImage: "/images/commenter6.jpg",
      },
    ],
  },
  {
    id: "3",
    userId: "3",
    boardId: "3",
    animalId: "3",
    title: "Beautiful Bird Video",
    content: "A stunning video of a bird in its natural habitat.",
    thumbnail: "/thumbnails/bird1.jpg",
    video: "/petpicks/video2.mp4",
    registTime: "2024-08-03T20:00:00",
    userNickname: "BirdWatcher1",
    userImage: "/images/user3.jpg",
    likeCnt: 100,
    isLiking: true,
    isFollowing: true,
    processState: "입양완료",
    kindCd: "[조류] 앵무새",
    name: "Sunny",
    comments: [
      {
        id: 7,
        userId: 7,
        petPickId: 3,
        content: "What a beautiful video! Amazing footage.",
        registTime: "2024-08-03T21:00:00",
        userNickname: "BirdFan7",
        userImage: "/images/commenter7.jpg",
      },
      {
        id: 8,
        userId: 8,
        petPickId: 3,
        content: "I love bird watching, thanks for this!",
        registTime: "2024-08-03T22:00:00",
        userNickname: "NatureLover8",
        userImage: "/images/commenter8.jpg",
      },
      {
        id: 9,
        userId: 9,
        petPickId: 3,
        content: "This made my day. Beautiful video!",
        registTime: "2024-08-03T23:00:00",
        userNickname: "BirdLover9",
        userImage: "/images/commenter9.jpg",
      },
    ],
  },
  {
    id: "4",
    userId: "4",
    boardId: "4",
    animalId: "4",
    title: "Amazing Fish Video",
    content: "An underwater video showcasing colorful fish.",
    thumbnail: "/thumbnails/fish1.jpg",
    video: "/petpicks/video3.mp4",
    registTime: "2024-08-04T00:00:00",
    userNickname: "AquaLover1",
    userImage: "/images/user4.jpg",
    likeCnt: 130,
    isLiking: false,
    isFollowing: true,
    processState: "입양완료",
    kindCd: "[어류] 열대어",
    name: "Nemo",
    comments: [
      {
        id: 10,
        userId: 10,
        petPickId: 4,
        content: "Such vibrant colors! Loved the video.",
        registTime: "2024-08-04T01:00:00",
        userNickname: "FishFan10",
        userImage: "/images/commenter10.jpg",
      },
      {
        id: 11,
        userId: 11,
        petPickId: 4,
        content: "Incredible footage! More like this please.",
        registTime: "2024-08-04T02:00:00",
        userNickname: "AquaFan11",
        userImage: "/images/commenter11.jpg",
      },
      {
        id: 12,
        userId: 12,
        petPickId: 4,
        content: "Amazing video, thanks for sharing!",
        registTime: "2024-08-04T03:00:00",
        userNickname: "FishLover12",
        userImage: "/images/commenter12.jpg",
      },
    ],
  },
  // 추가된 데이터
  {
    id: "5",
    userId: "5",
    boardId: "5",
    animalId: "5",
    title: "Adorable Hamster Video",
    content: "Watch this cute video of my hamster running in its wheel.",
    thumbnail: "/thumbnails/hamster1.jpg",
    video: "/petpicks/cat.mp4",
    registTime: "2024-08-04T04:00:00",
    userNickname: "HamsterLover1",
    userImage: "/images/user5.jpg",
    likeCnt: 85,
    isLiking: true,
    isFollowing: false,
    processState: "입양대기",
    kindCd: "[소동물] 햄스터",
    name: "Nibbles",
    comments: [
      {
        id: 13,
        userId: 13,
        petPickId: 5,
        content: "So adorable! Hamsters are the best.",
        registTime: "2024-08-04T05:00:00",
        userNickname: "SmallPetFan1",
        userImage: "/images/commenter13.jpg",
      },
      {
        id: 14,
        userId: 14,
        petPickId: 5,
        content: "Love watching hamsters run around!",
        registTime: "2024-08-04T06:00:00",
        userNickname: "PetLover14",
        userImage: "/images/commenter14.jpg",
      },
      {
        id: 15,
        userId: 15,
        petPickId: 5,
        content: "This video made me smile!",
        registTime: "2024-08-04T07:00:00",
        userNickname: "HappyViewer15",
        userImage: "/images/commenter15.jpg",
      },
    ],
  },
  {
    id: "6",
    userId: "6",
    boardId: "6",
    animalId: "6",
    title: "Playful Rabbit Video",
    content: "A video of my rabbit hopping around the garden.",
    thumbnail: "/thumbnails/rabbit1.jpg",
    video: "/petpicks/video.mp4",
    registTime: "2024-08-04T08:00:00",
    userNickname: "RabbitFan1",
    userImage: "/images/user6.jpg",
    likeCnt: 90,
    isLiking: false,
    isFollowing: true,
    processState: "임시보호",
    kindCd: "[소동물] 토끼",
    name: "Fluffy",
    comments: [
      {
        id: 16,
        userId: 16,
        petPickId: 6,
        content: "So cute! Rabbits are such playful animals.",
        registTime: "2024-08-04T09:00:00",
        userNickname: "BunnyLover16",
        userImage: "/images/commenter16.jpg",
      },
      {
        id: 17,
        userId: 17,
        petPickId: 6,
        content: "Love this video, more rabbit content please!",
        registTime: "2024-08-04T10:00:00",
        userNickname: "RabbitFan17",
        userImage: "/images/commenter17.jpg",
      },
      {
        id: 18,
        userId: 18,
        petPickId: 6,
        content: "Fluffy looks so happy!",
        registTime: "2024-08-04T11:00:00",
        userNickname: "JoyfulViewer18",
        userImage: "/images/commenter18.jpg",
      },
    ],
  },
]
export default data
